<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2hwahmu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2hwahmu/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2hwahmu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2hwahmu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2hwahmu\appProdProjectContainer([
    'container.build_hash' => '2hwahmu',
    'container.build_id' => '84cdc77c',
    'container.build_time' => 1601366822,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2hwahmu');
